payload:
  - 'DOMAIN-SUFFIX,pages.dev'
  - 'DOMAIN-SUFFIX,jsdelivr.net'
  - 'DOMAIN-SUFFIX,pnpm.io'
  - 'DOMAIN-SUFFIX,schemastore.org'
  - 'DOMAIN-SUFFIX,openapi-ts.dev'
  - 'DOMAIN-SUFFIX,eslint.org'
  - 'DOMAIN-SUFFIX,jetbrains.com'
  - 'DOMAIN-SUFFIX,codemc.io'
  - 'DOMAIN-SUFFIX,github.io'
  - 'DOMAIN-SUFFIX,peerjs.com'
  - 'DOMAIN-SUFFIX,tailwindcss.com'
  - 'DOMAIN-SUFFIX,fontshare.com'
  - 'DOMAIN-SUFFIX,fontsource.org'
  - 'DOMAIN-SUFFIX,react.gg'
  - 'DOMAIN-SUFFIX,gofiber.io'
  - 'DOMAIN-SUFFIX,zod.dev'